### ISSUE TITLE
Fb ads still showing

### ISSUE THREAD

**Issue by chaimite** [ethan-xd/ethan-xd.github.io#25]
![image](https://user-images.githubusercontent.com/45879814/196041664-283da62a-2d99-429b-a693-306e2429ff38.png)
![image](https://user-images.githubusercontent.com/45879814/196041684-afc29c10-a6e0-4785-9c94-d4bb63779cf0.png)

Hi,

I am using your script for fb but can still see ads on fb :(

**Comment by ethan-xd** [comment]
thanks for providing html.

looks like a lot of people have this width range, ill look into blocking it now.

**Comment by ethan-xd** [comment]
question: how often do the ads show up? just sometimes or all the time?

**Comment by chaimite** [comment]
> question: how often do the ads show up? just sometimes or all the time?

All the time.

**Comment by chaimite** [comment]
> thanks for providing html.
> 
> looks like i just need to extend the width range for this one. thanks

Mind if I ask you for more details on this? Just trying to understand it better.

**Comment by ethan-xd** [comment]
> Mind if I ask you for more details on this? Just trying to understand it better.

rn the main blocking method is via this line:

```facebook.com##:xpath(//div[@aria-posinset and .//*[name()='use']/parent::*[name()='svg' and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) > 56.885 and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) < 56.895]]):upward(6)``` (and equivalent for firefox which has different widths)

if you look the svg tag has a random margin-right and width tag, however they add up to _roughly_ the same value every time. it seems like some different OSes/browsers lead to different width ranges, but they seem to differ even when on the same OS and browser, like i checked on my windows 10 firefox and i get different width ranges to you. does that make sense?

**Comment by ethan-xd** [comment]
im not sure why you have a different width range leading to the ads to show up all the time. if they were blocked most of the time i could fix it by making the range larger, but looks like you have an entirely different range. idk

**Comment by ethan-xd** [comment]
i need to find a better method but this was the best i could get in the interim. there was a method done by my friend but it was very slow and caused flickering and the newsfeed to break.

**Comment by chaimite** [comment]
> i need to find a better method but this was the best i could get in the interim. there was a method done by my friend but it was very slow and caused flickering and the newsfeed to break.

Is it possible to get the value of the total width to a variable and then use that to set it?

**Comment by ethan-xd** [comment]
interesting i didnt know that 4k would cause the issue, because im on 1440p and it works fine on my 1080p monitor.

> Is it possible to get the value of the total width to a variable and then use that to set it?

i asked my friend this earlier and apparently theres no way to set a variable in xpath. also, the width is slightly randomized, e.g. from a range 58.9 to 59.1, so it could be something like 59.001

**Comment by brandon-lockaby** [comment]
![image](https://user-images.githubusercontent.com/968126/209733923-9f87cc63-0fc0-4b97-ad8a-764ddd3141ea.png)

**Comment by ohhai** [comment]
@ethan-xd  should this list work with "uBlock Origin" in Firefox?

**Comment by ethan-xd** [comment]
@ohhai it should, although ive noticed that for some reason it doesnt work on some other machines because the size of the sponsored element is different, i dont know why. i will take a look

@brandon-lockaby thanks for supplying html i can take a look

**Comment by ohhai** [comment]
@ethan-xd   do you mean some numbers from this parts?
Something doesn't work for me (sponsored blocks are visible) for such a setup and I want to check what could be the reason  
```
svg[style$="width: 56.8906px;"]
svg[style$="width: 59px;"]
number(substring-before(substring-after(@style, 'width:'), 'px'))) > 56.885
number(substring-before(substring-after(@style, 'width:'), 'px'))) < 56.895
number(substring-before(substring-after(@style, 'width:'), 'px'))) > 58.9
number(substring-before(substring-after(@style, 'width:'), 'px'))) < 59.1
```

**Comment by ethan-xd** [comment]
@ohhai you need to make those last 4 an actual xpath block, those wont work on their own. if you want to block between two values (gathered from svg width + margin-right, e.g. from brandons above example 132.166 + -74.158 = 58.008), you need to do:

    facebook.com##:xpath("//div[@aria-posinset and .//*[name()='use']/parent::*[name()='svg' and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) > 57.9 and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) < 58.1]]"):upward(6)

does that answer your question?

**Comment by ohhai** [comment]
@ethan-xd  thank you! My knowledge of web magic is limited so I just bruteforced the values which work for me in Firefox 108.0.1 + uBlock Origin 1.46.0
```
facebook.com##:xpath("//div[@aria-posinset and .//*[name()='use']/parent::*[name()='svg' and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) > 57.8 and (number(substring-before(substring-after(@style, 'margin-right:'), 'px')) + number(substring-before(substring-after(@style, 'width:'), 'px'))) < 57.9]]")
```
Just in case, this is the matched div code copied as "outer HTML" in Firefox's Inspector: https://pastebin.com/5AhKijsS

**Comment by ohhai** [comment]
For google and for people with insufficient knowledge like me: it's easy to search for working width values. I did it like this in Firefox:
- open your FB feed and scroll to see first ad which is not hidden
- open "developer tools" pane (F12). Firefox can search by xpath expressions, Chrome could be same I think:
-- https://bugzilla.mozilla.org/show_bug.cgi?id=963933#c47
-- https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_html/index.html#xpath-search
- Copy xpath expression from the non-working rule to "Search HTML" field in Inspector tab of Devtools pane. Press Enter and check if it find something. For me it was nothing.
- In that expression change computed width values to something much wider. For example: `> 40` and `< 70`. Press Enter again and ensure now it matches a lot of elements.
- Now make the difference narrower (for example `> 50` and `< 60`) and continue to smallest difference which should match only the ad elements. This iterations could be done in the same Inspector tab or you could copy the rule to Ublock ruleset, apply and refresh the page with FB feed.

**Comment by loveisfoss** [comment]
> For google and for people with insufficient knowledge like me: it's easy to search for working width values. I did it like this in Firefox:
> 
> * open your FB feed and scroll to see first ad which is not hidden
> * open "developer tools" pane (F12). Firefox can search by xpath expressions, Chrome could be same I think:
>   -- https://bugzilla.mozilla.org/show_bug.cgi?id=963933#c47
>   -- https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_html/index.html#xpath-search
> * Copy xpath expression from the non-working rule to "Search HTML" field in Inspector tab of Devtools pane. Press Enter and check if it find something. For me it was nothing.
> * In that expression change computed width values to something much wider. For example: `> 40` and `< 70`. Press Enter again and ensure now it matches a lot of elements.
> * Now make the difference narrower (for example `> 50` and `< 60`) and continue to smallest difference which should match only the ad elements. This iterations could be done in the same Inspector tab or you could copy the rule to Ublock ruleset, apply and refresh the page with FB feed.

So, is this solution something that is going to automatically come at some point with an update or should we do something ourselves manually?

**Comment by ohhai** [comment]
@loveisfoss   my guide described only manual actions. Even if coming automatically, seems like FB just did some update and my expression listed above now does not work even with `> 20 and < 90` width values. So this work needs regular support and updating the rules, with corrections for different browsers and blocker plugins maybe.

**Comment by ohhai** [comment]
@ethan-xd 
I see following "ad" parts in the code of "Sponsored" posts, can they be a filtering target? It might give more reliable rule if so, but it's not so easy I guess

```
<a class="x1i10hfl" href="/ads/about/?__cft__[0]=

<div class="x1iorvi4" data-ad-comet-preview="message" data-ad-preview="message">

<img alt="" class="x1ey2m1c" src="https://www.facebook.com/ads/image/?d=
```

**Comment by ethan-xd** [comment]
@ohhai If you can verify that information identifying ads is there _before_ mousing over, or otherwise interacting with, the post, and that ad tracking stuff isn't in a normal post (which it usually is to defer adblockers), then yes it's possible.

**Comment by loveisfoss** [comment]
Hey! I just noticed that ethan's lists work against Facebook Sponsored with the Scale setting set to 100% but do not work when it is set to 125% or 150% (Windows 11).

**Comment by agnostopowicz** [comment]
Hi!

Line below removes polish sponsored posts, but facebook is crashing :( Without uncomment that line I see all sponsored posts.

> `facebook.com##:xpath("//div[@aria-posinset and .//*[name()='svg' and substring-after(./*[name()='use']/attribute::*[starts-with(., '#')], '#')=//*[name()='text' and .='Sponsorowane']/@id]]"):upward(6):remove()`

console:
[www.facebook.com-1674740289286.log](https://github.com/ethan-xd/ethan-xd.github.io/files/10509903/www.facebook.com-1674740289286.log)

html:
[fb_html.txt](https://github.com/ethan-xd/ethan-xd.github.io/files/10509819/fb_html.txt)

Any ideas how to bypass this? Maybe by sending a message simulating that I saw that post?

**Comment by ethan-xd** [comment]
@agnostopowicz removing posts breaks the feed, and not removing causes flickering with that method, which is why its been commented out and abandoned

**Comment by ethan-xd** [comment]
Reopen if this is still an active issue
