### ISSUE TITLE
Sponsored Ads in Marketplace

### ISSUE THREAD

**Issue by jbokt** [ethan-xd/ethan-xd.github.io#26]
![fb2](https://user-images.githubusercontent.com/112625977/198541155-e940036b-26f6-4100-ad65-306a0a8e410d.jpg)
![fb1](https://user-images.githubusercontent.com/112625977/198541156-26eddc19-cce0-418a-8d9f-f26e8dfa2c23.jpg)

**Comment by jbokt** [comment]
https://rentry.co/t9ryu

**Comment by ethan-xd** [comment]
thanks for heads up

**Comment by ethan-xd** [comment]
![image](https://user-images.githubusercontent.com/24442053/198929825-485a117a-ca8e-417d-80a8-a0144aea68fb.png)
should be resolved now. please purge cache and try again
