### ISSUE TITLE
Stories are not shown when using your list

### ISSUE THREAD

**Issue by pitsi** [ethan-xd/ethan-xd.github.io#28]
As mentioned in the title, the stories people post on facebook are not visible when your list is active. They can be accessed from facebook.com/stories though, so it is not that big of an issue if someone knows their url.

**Comment by ethan-xd** [comment]
yes i block them because i find it annoying sorry lol, i will consider splitting the list

**Comment by pitsi** [comment]
Tbh, 2 months after opening the issue, I no longer remember where I found your list and if there was a clear list of what it blocks. I do not mind it blocking the stories, as soon as you are aware of it.

Good job though, well done :)

**Comment by pitsi** [comment]
Your facebook list does not (seem to) affect stories anymore, and I do not know if you changed anything this 1+ year since I opened the issue, so I am asking your permission to close it. Thank you :)
