### ISSUE TITLE
"suggested for you" ads on m.facebook.com

### ISSUE THREAD

**Issue by DetachHead** [ethan-xd/ethan-xd.github.io#7]
![Screenshot_20211015-180941](https://user-images.githubusercontent.com/57028336/137454365-b7c60525-9b2f-45aa-a04d-1c3b0f4d0859.png)

**Comment by ethan-xd** [comment]
theres a lot of things on m.facebook.com that arent blocked because i dont use it, you could be the ceo of that if you want
